import styles from '../styles/Home.module.css';
import Head from 'next/head';
import {useState} from 'react';

const Home = () => {
  const [username, setUsername] = useState ('');
  console.log(username)
  return (
    <div className={styles.container}>
      <Head>
        <title>My Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome!
        </h1>
        <form action="/dashboard">
          <input
            type="text"
            name='username'
            value={username}
            onChange= {e => setUsername(e.target.value)}
            className={styles.input}
            placeholder="Enter Github username..."
            required
          />
          <p className={styles.submit}>
            <button type="submit">SUBMIT</button>
          </p>
        </form>
      </main>
    </div>
  );
};

export default Home;