import styles from '../styles/Home.module.css';
import Head from 'next/head';
import { useState, useEffect } from 'react';
import SearchBar from '../components/SearchBar';
import Card from '../components/Card';

const Home = () => {
  const [username, setUsername] = useState('');
  const [userData, setUserData] = useState({});

  useEffect(() => {
    getUserData();
  }, [username]);

  const gitHubUrl = `https://api.github.com/users/${username}`;

  const getUserData = async () => {
    const response = await fetch(gitHubUrl);
    const jsonData = await response.json();
    if (jsonData && jsonData.message !== 'Not Found') {
      setUserData(jsonData);
      console.log(jsonData);
    } else if (username !== '') {
      console.log('Username does not exist');
    } else {
      setUserData({});
    }
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>My Dashboard</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div>
        <SearchBar username={username} setUsername={setUsername} />
        <Card userData={userData} />
      </div>
    </div>
  );
};

export default Home;
